"""Add appointment_id to Sale, enforce not null

Revision ID: 1415e686f7fa
Revises: 92892f443867
Create Date: 2025-09-08 13:06:15.535853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1415e686f7fa'
down_revision: Union[str, Sequence[str], None] = '92892f443867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'appointment_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'appointment_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
