"""Add offer_discont table

Revision ID: 20ada827c6da
Revises: d3df2b88bef0
Create Date: 2025-09-10 15:20:30.605029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20ada827c6da'
down_revision: Union[str, Sequence[str], None] = 'd3df2b88bef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers_discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=True),
    sa.Column('item_id', sa.UUID(), nullable=True),
    sa.Column('discount_type', sa.Enum('PERCENTAGE', 'FIXED', name='discounttype'), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers_discounts')
    # ### end Alembic commands ###
