"""add reference_no to invoice_payment

Revision ID: 47a605d00d06
Revises: 517e7b5ba334
Create Date: 2025-08-31 18:04:41.177921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a605d00d06'
down_revision: Union[str, Sequence[str], None] = '517e7b5ba334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payments', sa.Column('reference_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payments', 'reference_no')
    # ### end Alembic commands ###
