"""create invoices, invoice_items, invoice_payments tables

Revision ID: 517e7b5ba334
Revises: c2104a0c686b
Create Date: 2025-08-31 17:42:32.326790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '517e7b5ba334'
down_revision: Union[str, Sequence[str], None] = 'c2104a0c686b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_no', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_payments_id'), 'invoice_payments', ['id'], unique=False)
    op.drop_column('invoices', 'check')
    op.drop_column('invoices', 'custom')
    op.drop_column('invoices', 'gift_card')
    op.drop_column('invoices', 'prepaid_card')
    op.drop_column('invoices', 'cash')
    op.drop_column('invoices', 'lp')
    op.drop_column('invoices', 'card')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('card', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('lp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('cash', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('prepaid_card', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('gift_card', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('custom', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('check', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_invoice_payments_id'), table_name='invoice_payments')
    op.drop_table('invoice_payments')
    # ### end Alembic commands ###
