"""fix room-roomcategory relationship

Revision ID: 5ee2881ccfdd
Revises: 9c581b7afc47
Create Date: 2025-08-25 11:30:51.627005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee2881ccfdd'
down_revision: Union[str, Sequence[str], None] = '9c581b7afc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('rooms', 'center_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('rooms', 'dq_check_remark',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_constraint(op.f('rooms_code_key'), 'rooms', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('rooms_code_key'), 'rooms', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.alter_column('rooms', 'dq_check_remark',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('rooms', 'center_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('rooms', 'description',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
