"""remove relationships

Revision ID: 6145e5a5ac3f
Revises: f96ca071c754
Create Date: 2025-08-25 14:28:54.225073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6145e5a5ac3f'
down_revision: Union[str, Sequence[str], None] = 'f96ca071c754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('appointments', 'scheduled_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_constraint(op.f('appointments_provider_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_service_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_center_id_fkey'), 'appointments', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('appointments_center_id_fkey'), 'appointments', 'centers', ['center_id'], ['id'])
    op.create_foreign_key(op.f('appointments_service_id_fkey'), 'appointments', 'services', ['service_id'], ['id'])
    op.create_foreign_key(op.f('appointments_provider_id_fkey'), 'appointments', 'providers', ['provider_id'], ['id'])
    op.alter_column('appointments', 'scheduled_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
