"""Add discount_id to sales table

Revision ID: 6ad9616209c0
Revises: 20ada827c6da
Create Date: 2025-09-10 16:03:40.192907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad9616209c0'
down_revision: Union[str, Sequence[str], None] = '20ada827c6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('discount_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sales', 'offers_discounts', ['discount_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'discount_id')
    # ### end Alembic commands ###
