"""add sales and collections tables

Revision ID: 87eaba2c9c82
Revises: f736abc06253
Create Date: 2025-09-01 18:28:32.606395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87eaba2c9c82'
down_revision: Union[str, Sequence[str], None] = 'f736abc06253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sale_no', sa.String(), nullable=False),
    sa.Column('sale_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('gross_value', sa.Float(), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('net_value', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_no')
    )
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('collection_no', sa.String(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('transaction_no', sa.String(), nullable=True),
    sa.Column('reference_no', sa.String(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('employee_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_no')
    )
    op.create_index(op.f('ix_collections_id'), 'collections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###
