"""Add guest_code to guests

Revision ID: 8aa747aea0b3
Revises: 89121b8ff089
Create Date: 2025-08-28 16:19:38.501963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa747aea0b3'
down_revision: Union[str, Sequence[str], None] = '89121b8ff089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('guest_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_guests_guest_code'), 'guests', ['guest_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guests_guest_code'), table_name='guests')
    op.drop_column('guests', 'guest_code')
    # ### end Alembic commands ###
