"""Added feilds

Revision ID: 996a43d18cd9
Revises: 2f73c063d8d9
Create Date: 2025-08-29 11:33:39.174562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996a43d18cd9'
down_revision: Union[str, Sequence[str], None] = '2f73c063d8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'packages', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'packages', type_='foreignkey')
    op.drop_column('packages', 'category_id')
    # ### end Alembic commands ###
