"""create room_categories and rooms tables

Revision ID: 9c581b7afc47
Revises: 6d4827deaa89
Create Date: 2025-08-25 11:19:46.545897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c581b7afc47'
down_revision: Union[str, Sequence[str], None] = '6d4827deaa89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_categories', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_categories', 'description')
    # ### end Alembic commands ###
