"""create rooms table

Revision ID: a10236e8e3af
Revises: baa46b56d507
Create Date: 2025-08-25 10:56:23.229229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a10236e8e3af'
down_revision: Union[str, Sequence[str], None] = 'baa46b56d507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatus'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show', name='appointmentstatus'),
               nullable=True)
    # ### end Alembic commands ###
