"""fix relationships between appointment, sale, invoice, collection, guest

Revision ID: d3bcbc5f340b
Revises: 87eaba2c9c82
Create Date: 2025-09-02 12:38:47.654566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3bcbc5f340b'
down_revision: Union[str, Sequence[str], None] = '87eaba2c9c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('invoice_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'collections', 'invoices', ['invoice_id'], ['id'])
    op.add_column('invoices', sa.Column('sale_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'sales', ['sale_id'], ['id'])
    op.add_column('sales', sa.Column('appointment_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('sales_invoice_id_fkey'), 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'appointments', ['appointment_id'], ['id'])
    op.drop_column('sales', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key(op.f('sales_invoice_id_fkey'), 'sales', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('sales', 'appointment_id')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'sale_id')
    op.drop_constraint(None, 'collections', type_='foreignkey')
    op.drop_column('collections', 'invoice_id')
    # ### end Alembic commands ###
