"""add remarks to invoice_payment

Revision ID: f736abc06253
Revises: 47a605d00d06
Create Date: 2025-08-31 18:07:07.096174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f736abc06253'
down_revision: Union[str, Sequence[str], None] = '47a605d00d06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payments', sa.Column('remarks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_payments', 'remarks')
    # ### end Alembic commands ###
