"""update relationships sale-payment-invoice

Revision ID: f932bc83b916
Revises: 1c9fb52c301b
Create Date: 2025-09-11 10:54:10.195769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f932bc83b916'
down_revision: Union[str, Sequence[str], None] = '1c9fb52c301b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payments', sa.Column('sale_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('invoice_payments_invoice_id_fkey'), 'invoice_payments', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_payments', 'sales', ['sale_id'], ['id'])
    op.drop_column('invoice_payments', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_payments', sa.Column('invoice_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'invoice_payments', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_payments_invoice_id_fkey'), 'invoice_payments', 'invoices', ['invoice_id'], ['id'])
    op.drop_column('invoice_payments', 'sale_id')
    # ### end Alembic commands ###
