"""Created Package and business tables

Revision ID: fdee2b23ad19
Revises: 5f9dd969b495
Create Date: 2025-08-29 11:10:00.693505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdee2b23ad19'
down_revision: Union[str, Sequence[str], None] = '5f9dd969b495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_unit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_business_unit_id'), 'business_unit', ['id'], unique=False)
    op.create_table('packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('business_unit_id', sa.UUID(), nullable=True),
    sa.Column('version_id', sa.UUID(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('booking_start_date', sa.Date(), nullable=True),
    sa.Column('booking_end_date', sa.Date(), nullable=True),
    sa.Column('commission_eligible', sa.Boolean(), nullable=True),
    sa.Column('commission_factor', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('commission_type', sa.String(length=50), nullable=True),
    sa.Column('commission_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('series_package_type', sa.String(length=100), nullable=True),
    sa.Column('series_package_cost_to_center', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('center_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('dq_check_remark', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_unit_id'], ['business_unit.id'], ),
    sa.ForeignKeyConstraint(['center_id'], ['centers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_packages_id'), 'packages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_packages_id'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_business_unit_id'), table_name='business_unit')
    op.drop_table('business_unit')
    # ### end Alembic commands ###
